package rs.ac.bg.fon.micro_medic_monolith_backend.service;

import org.springframework.stereotype.Service;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.Doctor;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.Examination;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.Medicine;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.MedicineUsage;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.Patient;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.Report;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.ScheduledAppointment;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.SpecializationDepartment;
import rs.ac.bg.fon.micro_medic_monolith_backend.domain.Therapy;

import java.io.ByteArrayOutputStream;
import java.nio.charset.Charset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Renders examination reports as PDF.
 */
@Service
public class PdfGenerationService {

    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("dd.MM.yyyy. HH:mm");
    private static final Charset PDF_TEXT_CHARSET = Charset.forName("windows-1252");

    private static final int PAGE_WIDTH = 595;
    private static final int PAGE_HEIGHT = 842;
    private static final int MARGIN = 56;
    private static final int TITLE_SIZE = 17;
    private static final int HEADING_SIZE = 12;
    private static final int BODY_SIZE = 10;

    public byte[] generateExaminationReportPdf(Report report, Examination examination, Therapy therapy) {
        if (report == null) {
            throw new IllegalArgumentException("Report cannot be null");
        }

        return render(paginate(describe(report, examination, therapy)));
    }

    private record Line(String text, int size, boolean bold) {
        static Line title(String text) {
            return new Line(text, TITLE_SIZE, true);
        }

        static Line heading(String text) {
            return new Line(text, HEADING_SIZE, true);
        }

        static Line body(String text) {
            return new Line(text, BODY_SIZE, false);
        }

        static Line blank() {
            return new Line("", BODY_SIZE, false);
        }
    }

    private List<Line> describe(Report report, Examination examination, Therapy therapy) {
        List<Line> lines = new ArrayList<>();

        lines.add(Line.title(report.getTitle() != null ? report.getTitle() : "Examination Report"));
        lines.add(Line.body("Report #" + (report.getId() != null ? report.getId() : "N/A")));

        if (report.getCreationTime() != null) {
            lines.add(Line.body("Generated: " + DATE_TIME_FORMATTER.format(report.getCreationTime())));
        }

        if (report.getGeneratedBy() != null) {
            var author = report.getGeneratedBy();
            StringBuilder generatedBy = new StringBuilder();
            generatedBy.append("Generated by: ")
                    .append(author.getFirstname()).append(' ')
                    .append(author.getLastname());
            if (author.getEmail() != null) {
                generatedBy.append(" (").append(author.getEmail()).append(')');
            }
            lines.add(Line.body(generatedBy.toString()));
        }

        lines.add(Line.blank());

        if (examination != null) {
            addExamination(lines, examination);
        }

        if (therapy != null) {
            addTherapy(lines, therapy);
        }

        return lines;
    }

    private void addExamination(List<Line> lines, Examination examination) {
        lines.add(Line.heading("Examination"));

        if (examination.getStart() != null) {
            lines.add(Line.body("Start: " + DATE_TIME_FORMATTER.format(examination.getStart())));
        }
        if (examination.getEnd() != null) {
            lines.add(Line.body("End: " + DATE_TIME_FORMATTER.format(examination.getEnd())));
        }
        if (examination.getStatus() != null) {
            lines.add(Line.body("Status: " + examination.getStatus().name()));
        }

        ScheduledAppointment appointment = examination.getScheduledAppointment();
        if (appointment != null) {
            Patient patient = appointment.getPatient();
            if (patient != null) {
                StringBuilder patientLine = new StringBuilder();
                patientLine.append("Patient: ").append(patient.getFirstname()).append(' ').append(patient.getLastname());
                if (patient.getId() != null) {
                    patientLine.append(" (ID ").append(patient.getId()).append(')');
                }
                lines.add(Line.body(patientLine.toString()));
            }

            Doctor doctor = appointment.getDoctor();
            if (doctor != null) {
                lines.add(Line.body("Doctor: " + doctor.getFirstname() + " " + doctor.getLastname()));

                SpecializationDepartment specialization = doctor.getSpecialization();
                if (specialization != null) {
                    lines.add(Line.body("Specialization: " + specialization.getName()));
                }
            }
        }

        if (examination.getDiagnosis() != null) {
            var diagnosis = examination.getDiagnosis();
            StringBuilder diagnosisLine = new StringBuilder();
            diagnosisLine.append("Diagnosis: ").append(diagnosis.getCode());
            if (diagnosis.getDescription() != null && !diagnosis.getDescription().isBlank()) {
                diagnosisLine.append(" - ").append(diagnosis.getDescription());
            }
            lines.add(Line.body(diagnosisLine.toString()));
        }

        lines.add(Line.blank());
        lines.add(Line.heading("Anamnesis"));
        addWrapped(lines, examination.getAnamnesis(), "-");
        lines.add(Line.blank());
    }

    private void addTherapy(List<Line> lines, Therapy therapy) {
        lines.add(Line.heading("Therapy"));
        addWrapped(lines, therapy.getInstructions(), "-");
        lines.add(Line.blank());

        List<MedicineUsage> usages = therapy.getMedicineUsages();
        lines.add(Line.heading("Prescribed medication"));
        if (usages == null || usages.isEmpty()) {
            lines.add(Line.body("None."));
            return;
        }

        for (MedicineUsage usage : usages) {
            Medicine medicine = usage.getMedicine();
            StringBuilder name = new StringBuilder();
            if (medicine == null) {
                name.append("Unknown medicine");
            } else {
                name.append(medicine.getGenericName() != null ? medicine.getGenericName() : "Unknown medicine");
                if (medicine.getBrandName() != null && !medicine.getBrandName().isBlank()) {
                    name.append(" (").append(medicine.getBrandName()).append(')');
                }
                if (medicine.getForm() != null) {
                    name.append(", ").append(medicine.getForm().getName());
                }
            }

            addWrapped(lines, name.toString(), null);

            StringBuilder schedule = new StringBuilder();
            schedule.append("Method: ").append(usage.getMethodUse());
            if (usage.getFrequencyIntakeInHours() != null) {
                schedule.append(", every ").append(usage.getFrequencyIntakeInHours()).append('h');
            }
            addWrapped(lines, schedule.toString(), null);
        }
    }

    private void addWrapped(List<Line> lines, String text, String fallback) {
        String value = text == null || text.isBlank() ? fallback : text;
        if (value == null || value.isBlank()) {
            return;
        }

        for (String wrapped : wrap(value, BODY_SIZE)) {
            lines.add(Line.body(wrapped));
        }
    }

    private List<String> wrap(String text, int fontSize) {
        int maxChars = Math.max(20, (int) ((PAGE_WIDTH - 2.0 * MARGIN) / (0.5 * fontSize)));

        List<String> wrappedLines = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        for (String word : text.split("\\s+")) {
            if (word.isEmpty()) {
                continue;
            }

            if (current.isEmpty()) {
                current.append(word);
            } else if (current.length() + 1 + word.length() <= maxChars) {
                current.append(' ').append(word);
            } else {
                wrappedLines.add(current.toString());
                current.setLength(0);
                current.append(word);
            }
        }

        if (!current.isEmpty()) {
            wrappedLines.add(current.toString());
        }

        return wrappedLines.isEmpty() ? List.of("") : wrappedLines;
    }

    private List<List<Line>> paginate(List<Line> lines) {
        int usableHeight = PAGE_HEIGHT - 2 * MARGIN;
        List<List<Line>> pages = new ArrayList<>();
        List<Line> currentPage = new ArrayList<>();
        int currentHeight = 0;

        for (Line line : lines) {
            int lineHeight = lineHeight(line);
            if (!currentPage.isEmpty() && currentHeight + lineHeight > usableHeight) {
                pages.add(currentPage);
                currentPage = new ArrayList<>();
                currentHeight = 0;
            }

            currentPage.add(line);
            currentHeight += lineHeight;
        }

        if (currentPage.isEmpty()) {
            currentPage.add(Line.blank());
        }

        pages.add(currentPage);
        return pages;
    }

    private int lineHeight(Line line) {
        return Math.max(14, line.size() + 6);
    }

    private byte[] render(List<List<Line>> pages) {
        List<byte[]> objects = new ArrayList<>();

        StringBuilder kids = new StringBuilder();
        for (int i = 0; i < pages.size(); i++) {
            if (i > 0) {
                kids.append(' ');
            }
            kids.append(5 + 2 * i).append(" 0 R");
        }

        objects.add(ascii("<</Type /Catalog /Pages 2 0 R>>"));
        objects.add(ascii("<</Type /Pages /Kids [" + kids + "] /Count " + pages.size() + ">>"));
        objects.add(ascii("<</Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding>>"));
        objects.add(ascii("<</Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding>>"));

        for (int i = 0; i < pages.size(); i++) {
            int contentObjectNumber = 6 + 2 * i;
            objects.add(ascii("<</Type /Page /Parent 2 0 R /MediaBox [0 0 " + PAGE_WIDTH + ' ' + PAGE_HEIGHT + "] /Resources <</Font <</F1 3 0 R /F2 4 0 R>>>> /Contents " + contentObjectNumber + " 0 R>>"));
            objects.add(streamObject(contentStream(pages.get(i))));
        }

        return assemble(objects);
    }

    private String contentStream(List<Line> lines) {
        StringBuilder content = new StringBuilder();
        int y = PAGE_HEIGHT - MARGIN;

        for (Line line : lines) {
            int lineStep = lineHeight(line);
            if (!line.text().isEmpty()) {
                content.append("BT\n")
                        .append('/').append(line.bold() ? "F2" : "F1").append(' ').append(line.size()).append(" Tf\n")
                        .append("1 0 0 1 ").append(MARGIN).append(' ').append(y).append(" Tm\n")
                        .append('(').append(escape(line.text())).append(") Tj\n")
                        .append("ET\n");
            }
            y -= lineStep;
        }

        return content.toString();
    }

    private byte[] streamObject(String content) {
        byte[] body = content.getBytes(PDF_TEXT_CHARSET);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        write(out, ascii("<</Length " + body.length + ">>\nstream\n"));
        write(out, body);
        write(out, ascii("\nendstream"));
        return out.toByteArray();
    }

    private byte[] assemble(List<byte[]> objects) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        write(out, ascii("%PDF-1.4\n"));

        int[] offsets = new int[objects.size()];
        for (int i = 0; i < objects.size(); i++) {
            offsets[i] = out.size();
            write(out, ascii((i + 1) + " 0 obj\n"));
            write(out, objects.get(i));
            write(out, ascii("\nendobj\n"));
        }

        int xrefOffset = out.size();
        StringBuilder xref = new StringBuilder();
        xref.append("xref\n0 ").append(objects.size() + 1).append('\n');
        xref.append("0000000000 65535 f \n");
        for (int offset : offsets) {
            xref.append(String.format("%010d 00000 n \n", offset));
        }

        xref.append("trailer\n<</Size ").append(objects.size() + 1).append("/Root 1 0 R>>\n")
                .append("startxref\n").append(xrefOffset).append("\n%%EOF\n");
        write(out, ascii(xref.toString()));

        return out.toByteArray();
    }

    private String escape(String text) {
        StringBuilder escaped = new StringBuilder(text.length() + 8);
        for (char c : text.toCharArray()) {
            switch (c) {
                case '\\', '(', ')' -> escaped.append('\\').append(c);
                case '\r', '\n', '\t' -> escaped.append(' ');
                default -> escaped.append(c);
            }
        }
        return escaped.toString();
    }

    private byte[] ascii(String text) {
        return text.getBytes(PDF_TEXT_CHARSET);
    }

    private void write(ByteArrayOutputStream out, byte[] bytes) {
        out.write(bytes, 0, bytes.length);
    }
}
